/*
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.idea.facet;

import com.intellij.facet.Facet;
import com.intellij.facet.FacetTypeId;
import org.eclipse.xtext.idea.facet.AbstractFacetType;
import org.metaborg.paplj.idea.lang.PapljLanguage;

public class PapljFacetType extends AbstractFacetType<PapljFacetConfiguration> {

	public static final FacetTypeId<Facet<PapljFacetConfiguration>> TYPEID = new FacetTypeId<Facet<PapljFacetConfiguration>>("org.metaborg.paplj.Paplj");

	public PapljFacetType() {
		super(TYPEID, "org.metaborg.paplj.Paplj", "Paplj");
		PapljLanguage.INSTANCE.injectMembers(this);
	}
}
