/*
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class PapljIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new PapljStandaloneSetupIdea().createInjector
	}

}
