/*
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class PapljIdeaModule extends AbstractPapljIdeaModule {
}
