/*
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.idea.completion;

import org.eclipse.xtext.common.idea.completion.TerminalsCompletionContributor;
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public class AbstractPapljCompletionContributor extends TerminalsCompletionContributor {
	public AbstractPapljCompletionContributor(AbstractXtextLanguage lang) {
		super(lang);
	}
}
