/**
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.idea.highlighting;

import org.metaborg.paplj.idea.highlighting.PapljBaseColorSettingsPage;

@SuppressWarnings("all")
public class PapljColorSettingsPage extends PapljBaseColorSettingsPage {
}
