/*
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.idea.completion

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage
import org.metaborg.paplj.idea.lang.PapljLanguage

class PapljCompletionContributor extends AbstractPapljCompletionContributor {
	new() {
		this(PapljLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
