/**
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.web;

import org.metaborg.paplj.web.AbstractPapljWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class PapljWebModule extends AbstractPapljWebModule {
}
