/**
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.metaborg.paplj.PapljRuntimeModule;
import org.metaborg.paplj.PapljStandaloneSetup;
import org.metaborg.paplj.ide.PapljIdeModule;
import org.metaborg.paplj.web.PapljWebModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class PapljWebSetup extends PapljStandaloneSetup {
  @Override
  public Injector createInjector() {
    PapljRuntimeModule _papljRuntimeModule = new PapljRuntimeModule();
    PapljIdeModule _papljIdeModule = new PapljIdeModule();
    PapljWebModule _papljWebModule = new PapljWebModule();
    return Guice.createInjector(Modules2.mixin(_papljRuntimeModule, _papljIdeModule, _papljWebModule));
  }
}
