/**
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.metaborg.paplj.ui.AbstractPapljUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class PapljUiModule extends AbstractPapljUiModule {
  public PapljUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
