/**
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.idea;

import com.google.inject.Injector;
import org.metaborg.paplj.PapljStandaloneSetupGenerated;

@SuppressWarnings("all")
public class PapljStandaloneSetupIdea extends PapljStandaloneSetupGenerated {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from PapljIdeaModule to Module");
  }
}
