/**
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.idea;

import org.metaborg.paplj.idea.AbstractPapljIdeaModule;

/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
@SuppressWarnings("all")
public class PapljIdeaModule extends AbstractPapljIdeaModule {
}
