/**
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.idea;

import com.google.inject.Injector;
import org.eclipse.xtext.ISetup;

@SuppressWarnings("all")
public class PapljIdeaSetup implements ISetup {
  @Override
  public Injector createInjectorAndDoEMFRegistration() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field EcoreGlobalRegistries is undefined"
      + "\nensureInitialized cannot be resolved");
  }
}
