/*
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.idea;

import com.intellij.openapi.extensions.ExtensionFactory;
import org.metaborg.paplj.idea.lang.PapljLanguage;

public class PapljExtensionFactory implements ExtensionFactory {
	@Override
	public Object createInstance(String factoryArgument, String implementationClass) {
		Class<?> clazz;
		try {
			clazz = Class.forName(implementationClass);
		} catch (ClassNotFoundException e) {
			throw new IllegalArgumentException("Couldn't load "+implementationClass, e);
		}
		return PapljLanguage.INSTANCE.<Object> getInstance(clazz);
	}
}
