/**
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.paplj;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Binding</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.metaborg.paplj.paplj.Binding#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.metaborg.paplj.paplj.PapljPackage#getBinding()
 * @model
 * @generated
 */
public interface Binding extends Symbol
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(Expr)
   * @see org.metaborg.paplj.paplj.PapljPackage#getBinding_Value()
   * @model containment="true"
   * @generated
   */
  Expr getValue();

  /**
   * Sets the value of the '{@link org.metaborg.paplj.paplj.Binding#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(Expr value);

} // Binding
