/**
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.paplj;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Block2</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.metaborg.paplj.paplj.Block2#getExprs <em>Exprs</em>}</li>
 * </ul>
 *
 * @see org.metaborg.paplj.paplj.PapljPackage#getBlock2()
 * @model
 * @generated
 */
public interface Block2 extends Expr
{
  /**
   * Returns the value of the '<em><b>Exprs</b></em>' containment reference list.
   * The list contents are of type {@link org.metaborg.paplj.paplj.Expr}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exprs</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exprs</em>' containment reference list.
   * @see org.metaborg.paplj.paplj.PapljPackage#getBlock2_Exprs()
   * @model containment="true"
   * @generated
   */
  EList<Expr> getExprs();

} // Block2
