/**
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.paplj;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bool</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.metaborg.paplj.paplj.Bool#isTrue <em>True</em>}</li>
 * </ul>
 *
 * @see org.metaborg.paplj.paplj.PapljPackage#getBool()
 * @model
 * @generated
 */
public interface Bool extends Expr
{
  /**
   * Returns the value of the '<em><b>True</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>True</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>True</em>' attribute.
   * @see #setTrue(boolean)
   * @see org.metaborg.paplj.paplj.PapljPackage#getBool_True()
   * @model
   * @generated
   */
  boolean isTrue();

  /**
   * Sets the value of the '{@link org.metaborg.paplj.paplj.Bool#isTrue <em>True</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>True</em>' attribute.
   * @see #isTrue()
   * @generated
   */
  void setTrue(boolean value);

} // Bool
