/**
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.paplj;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Field</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.metaborg.paplj.paplj.PapljPackage#getField()
 * @model
 * @generated
 */
public interface Field extends Member
{
} // Field
