/**
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.paplj;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Member</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.metaborg.paplj.paplj.PapljPackage#getMember()
 * @model
 * @generated
 */
public interface Member extends Symbol
{
} // Member
