/**
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.paplj;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Member Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.metaborg.paplj.paplj.MemberRef#getLeft <em>Left</em>}</li>
 *   <li>{@link org.metaborg.paplj.paplj.MemberRef#getMember <em>Member</em>}</li>
 *   <li>{@link org.metaborg.paplj.paplj.MemberRef#isMethodInvocation <em>Method Invocation</em>}</li>
 *   <li>{@link org.metaborg.paplj.paplj.MemberRef#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @see org.metaborg.paplj.paplj.PapljPackage#getMemberRef()
 * @model
 * @generated
 */
public interface MemberRef extends Expr
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Left</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(Expr)
   * @see org.metaborg.paplj.paplj.PapljPackage#getMemberRef_Left()
   * @model containment="true"
   * @generated
   */
  Expr getLeft();

  /**
   * Sets the value of the '{@link org.metaborg.paplj.paplj.MemberRef#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(Expr value);

  /**
   * Returns the value of the '<em><b>Member</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Member</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Member</em>' reference.
   * @see #setMember(Member)
   * @see org.metaborg.paplj.paplj.PapljPackage#getMemberRef_Member()
   * @model
   * @generated
   */
  Member getMember();

  /**
   * Sets the value of the '{@link org.metaborg.paplj.paplj.MemberRef#getMember <em>Member</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Member</em>' reference.
   * @see #getMember()
   * @generated
   */
  void setMember(Member value);

  /**
   * Returns the value of the '<em><b>Method Invocation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Method Invocation</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Method Invocation</em>' attribute.
   * @see #setMethodInvocation(boolean)
   * @see org.metaborg.paplj.paplj.PapljPackage#getMemberRef_MethodInvocation()
   * @model
   * @generated
   */
  boolean isMethodInvocation();

  /**
   * Sets the value of the '{@link org.metaborg.paplj.paplj.MemberRef#isMethodInvocation <em>Method Invocation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Method Invocation</em>' attribute.
   * @see #isMethodInvocation()
   * @generated
   */
  void setMethodInvocation(boolean value);

  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference list.
   * The list contents are of type {@link org.metaborg.paplj.paplj.Expr}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Args</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference list.
   * @see org.metaborg.paplj.paplj.PapljPackage#getMemberRef_Args()
   * @model containment="true"
   * @generated
   */
  EList<Expr> getArgs();

} // MemberRef
