/**
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.paplj;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>This</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.metaborg.paplj.paplj.PapljPackage#getThis()
 * @model
 * @generated
 */
public interface This extends Expr
{
} // This
