/**
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.idea.completion;

import org.metaborg.paplj.idea.completion.AbstractPapljCompletionContributor;

@SuppressWarnings("all")
public class PapljCompletionContributor extends AbstractPapljCompletionContributor {
  public PapljCompletionContributor() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe constructor PapljCompletionContributor(AbstractXtextLanguage) refers to the missing type AbstractXtextLanguage");
  }
  
  public PapljCompletionContributor(final /* AbstractXtextLanguage */Object lang) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(AbstractXtextLanguage) is undefined");
  }
}
