/*
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.idea.lang;

import com.intellij.lang.Language;
import com.intellij.openapi.fileTypes.LanguageFileType;
import javax.swing.Icon;
import org.eclipse.xtext.idea.Icons;
import org.jetbrains.annotations.NonNls;

public class AbstractPapljFileType extends LanguageFileType {

	@NonNls 
	public static final String DEFAULT_EXTENSION = "pj";

	protected AbstractPapljFileType(final Language language) {
		super(language);
	}

	@Override
	public String getDefaultExtension() {
		return DEFAULT_EXTENSION;
	}

	@Override
	public String getDescription() {
		return "Paplj files";
	}

	@Override
	public Icon getIcon() {
		return Icons.DSL_FILE_TYPE;
	}

	@Override
	public String getName() {
		return "Paplj";
	}

}
