/*
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.idea.lang;

import com.intellij.openapi.fileTypes.FileTypeConsumer;
import com.intellij.openapi.fileTypes.FileTypeFactory;
import org.jetbrains.annotations.NotNull;

public class PapljFileTypeFactory extends FileTypeFactory {

	@Override
	public void createFileTypes(@NotNull FileTypeConsumer consumer) {
		consumer.consume(PapljFileType.INSTANCE, AbstractPapljFileType.DEFAULT_EXTENSION);
	}

}
