/*
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.idea.lang;

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public final class PapljLanguage extends AbstractXtextLanguage {

	public static final PapljLanguage INSTANCE = new PapljLanguage();

	private PapljLanguage() {
		super("org.metaborg.paplj.Paplj");
	}

}
