/**
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.paplj.impl;

import org.eclipse.emf.ecore.EClass;

import org.metaborg.paplj.paplj.PapljPackage;
import org.metaborg.paplj.paplj.This;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>This</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ThisImpl extends ExprImpl implements This
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ThisImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PapljPackage.Literals.THIS;
  }

} //ThisImpl
