/**
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.ide;

import org.metaborg.paplj.ide.AbstractPapljIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class PapljIdeModule extends AbstractPapljIdeModule {
}
