/*
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.idea.lang.psi;

import com.intellij.psi.util.PsiModificationTracker;
import org.eclipse.xtext.psi.BaseXtextCodeBlockModificationListener;
import org.metaborg.paplj.idea.lang.PapljLanguage;

public class PapljCodeBlockModificationListener extends BaseXtextCodeBlockModificationListener {

	public PapljCodeBlockModificationListener(PsiModificationTracker psiModificationTracker) {
		super(PapljLanguage.INSTANCE, psiModificationTracker);
	}

}
