/*
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.idea.lang


class PapljFileType extends AbstractPapljFileType {
	public static final PapljFileType INSTANCE = new PapljFileType()
	
	new() {
		super(PapljLanguage.INSTANCE)
	}
}
