/*
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.ui.wizard;

import org.eclipse.xtext.ui.wizard.XtextNewProjectWizard;

import org.eclipse.xtext.ui.wizard.IExtendedProjectInfo;
import org.eclipse.xtext.ui.wizard.IProjectCreator;
import com.google.inject.Inject;

public class PapljNewProjectWizard extends XtextNewProjectWizard {

	private PapljWizardNewProjectCreationPage mainPage;

	@Inject
	public PapljNewProjectWizard(IProjectCreator projectCreator) {
		super(projectCreator);
		setWindowTitle("New Paplj Project");
	}

	protected PapljWizardNewProjectCreationPage getMainPage() {
		return mainPage;
	}

	/**
	 * Use this method to add pages to the wizard.
	 * The one-time generated version of this class will add a default new project page to the wizard.
	 */
	@Override
	public void addPages() {
		mainPage = createMainPage("basicNewProjectPage");
		mainPage.setTitle("Paplj Project");
		mainPage.setDescription("Create a new Paplj project.");
		addPage(mainPage);
	}

	protected PapljWizardNewProjectCreationPage createMainPage(String pageName) {
		return new PapljWizardNewProjectCreationPage(pageName);
	}

	/**
	 * Use this method to read the project settings from the wizard pages and feed them into the project info class.
	 */
	@Override
	protected IExtendedProjectInfo getProjectInfo() {
		PapljProjectInfo projectInfo = new PapljProjectInfo();
		projectInfo.setProjectName(mainPage.getProjectName());
		if (!mainPage.useDefaults()) {
			projectInfo.setLocationPath(mainPage.getLocationPath());
		}
		return projectInfo;
	}

}
