/**
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.idea.facet;

/* @State(, ) */@SuppressWarnings("all")
public class PapljFacetConfiguration /* implements AbstractFacetConfiguration, PersistentStateComponent<GeneratorConfigurationState>  */{
}
