/*
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.idea.lang.psi.impl;

import com.intellij.openapi.fileTypes.FileType;
import com.intellij.psi.FileViewProvider;
import org.eclipse.xtext.psi.impl.BaseXtextFile;
import org.metaborg.paplj.idea.lang.PapljFileType;
import org.metaborg.paplj.idea.lang.PapljLanguage;

public final class PapljFileImpl extends BaseXtextFile {

	public PapljFileImpl(FileViewProvider viewProvider) {
		super(viewProvider, PapljLanguage.INSTANCE);
	}

	@Override
	public FileType getFileType() {
		return PapljFileType.INSTANCE;
	}
}
