/*
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPapljScopeProvider extends DelegatingScopeProvider {
}
