/*
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.idea.lang.pom;

import org.eclipse.xtext.idea.pom.AbstractXtextPomDeclarationSearcher;
import org.metaborg.paplj.idea.lang.PapljLanguage;

public class PapljPomDeclarationSearcher extends AbstractXtextPomDeclarationSearcher {

	public PapljPomDeclarationSearcher() {
		super(PapljLanguage.INSTANCE);
	}
}
