/*
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link PapljWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractPapljWebModule extends DefaultWebModule {

}
