/*
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PapljAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/metaborg/paplj/parser/antlr/internal/InternalPaplj.tokens");
	}
}
