/**
 * generated by Xtext 2.11.0
 */
package org.metaborg.paplj.idea.lang;

import org.metaborg.paplj.idea.lang.AbstractPapljFileType;

@SuppressWarnings("all")
public class PapljFileType extends AbstractPapljFileType {
  public final static PapljFileType INSTANCE = new PapljFileType();
  
  public PapljFileType() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(PapljLanguage) is undefined");
  }
}
